### ISSUE TITLE
Option to skip compact themes on Firefox 53+

### ISSUE THREAD

**Issue by adrianiainlam** [drsjb80/personaswitcher#21]
Just upgraded to FF 53, we were forced to have two new themes, "Compact Dark" and "Compact Light", and we cannot remove them from FF.
Is it possible to add an option to not rotate through these?
Alternatively, do you know of a way to remove these themes from FF?
Thanks.

**Comment by drsjb80** [comment]
We'll take a look and see what we can find. Thanks!

**Comment by drsjb80** [comment]
What we've done is more them to the bottom and ignore them. I'll put the new version up ASAP. Thanks!

**Comment by adrianiainlam** [comment]
Using the dev channel version now, I can confirm it is working great. Thank you very much!
