### ISSUE TITLE
No icon in Add-ons Manager, Firefox 54 — Ubuntu 14.04

### ISSUE THREAD

**Issue by graciecat** [drsjb80/personaswitcher#33]
In Firefox 54.0 (64-bit) installed in Ubuntu 14.04, the icon is missing in the Add-ons Manager list, as illustrated below:

[Missing icon in list](https://s6.postimg.org/5ggcicx0x/No_icon_Persona_Switcher.png)

**Comment by drsjb80** [comment]
Thanks very much for the report, we'll find out what's wrong and fix it.

**Comment by drsjb80** [comment]
Fixed in all new versions. Thanks!
