### ISSUE TITLE
Ignore Firefox 63 Light/Dark themes

### ISSUE THREAD

**Issue by adrianiainlam** [drsjb80/personaswitcher#38]
Hi.

Similar to #35 it seems that the new Firefox 63 broke this wonderful extension again...

The "Default" theme still gets ignored, but the "Light" and "Dark" themes are included.

**Comment by drsjb80** [comment]
Yeah, I noticed :/  We'll take a look. Thanks!

**Comment by drsjb80** [comment]
Fixed and published. Thanks much!
